### ISSUE TITLE
Crashes with newest version of BdLib

### ISSUE THREAD

**Issue by superJK92iscool** [CleanroomMC/Scalar#3]
CleanroomMC discord name: superJK92
https://mclo.gs/y7FClai 

It is a modified version of the Skyfactory 4 modpack using AE2 UEL:Extended and AE2 Stuff Unofficial: Extended.

**Comment by superJK92iscool** [comment]
Also it only started doing that after switching to Cleanroom Loader

**Comment by kappa-maintainer** [comment]
Read the readme and use 2.11.1
